# Generated by Django 5.2.8 on 2026-08-15 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('MERGE', 'Merge PDFs'), ('SPLIT', 'Split PDF'), ('CONVERT', 'Convert to PDF'), ('IMAGE_TO_PDF', 'Images to PDF'), ('WATERMARK', 'Watermark PDF'), ('ROTATE', 'Rotate PDF')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='toolkit_outputs/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Job',
                'verbose_name_plural': 'Tool Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
