# Generated by Django 5.2.8 on 2026-08-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='resume_report',
            new_name='ai_recommendations',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='resume_evidence',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
