# Generated by Django 5.2.8 on 2026-08-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_rename_resume_report_resumeanalysis_ai_recommendations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='candidate_profile',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='career_matches',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='resume_evidence',
        ),
    ]
