# Generated by Django, manually reordered to drop the
# unique_together index BEFORE removing its columns --
# MySQL/PyMySQL errors ("Key column ... doesn't exist")
# if the column is removed first.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0004_remove_resumeanalysis_candidate_profile_and_more'),
    ]

    operations = [
        # Drop the unique_together constraint FIRST, while both
        # columns it references still exist.
        migrations.AlterUniqueTogether(
            name='jobroleskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobroleskill',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='jobroleskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
        migrations.DeleteModel(
            name='JobRoleSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
