# Generated by Django 5.2.8 on 2026-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_error',
            field=models.TextField(blank=True, default='', help_text='Stores the last AI processing error for debugging.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of AI processing retry attempts.'),
        ),
    ]
